// <auto-generated />
namespace WebApplication2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class rmovedAttributeMin18years : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(rmovedAttributeMin18years));
        
        string IMigrationMetadata.Id
        {
            get { return "202001221034317_rmovedAttributeMin18years"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
